### ISSUE TITLE
Bitcoin miner?

### ISSUE THREAD

**Issue by ReubenKTSpace** [ramzialhaddadtm/isitweekaorweekb#1]
You have a bitcoin miner which is really sad, maybe atleast put the warning back on?

**Comment by ramzialhaddad** [comment]
The warning is there and also its a monero miner

**Comment by ReubenKTSpace** [comment]
Please check the actual website, I've checked multiple computers and
there's still no warning, so it's not a local problem
Also I think Web miners are illegal so be careful

**Comment by ramzialhaddad** [comment]
![proof](https://user-images.githubusercontent.com/5371012/36033239-dbf3cd06-0dc9-11e8-9fe8-170acad842d9.PNG)

**Comment by ramzialhaddad** [comment]
what more do you want? mate i run the site ik what im doing

**Comment by ramzialhaddad** [comment]
its even on mobile

**Comment by ReubenKTSpace** [comment]
Send me ur number or discord tag to my email
infinityace2002@gmail.com

**Comment by ramzialhaddad** [comment]
go on the website and join the school discord we can talk more there

**Comment by ReubenKTSpace** [comment]
For your sake as well as mine, I rather make it private

**Comment by ramzialhaddad** [comment]
yeah join so i can get your discord tag and stuff dw we dont have to chat there
